version: "3.8"

services:
  api:
    build:
      context: ./src
      dockerfile: DeveloperStore.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mongo
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=developerstore;Username=postgres;Password=postgres

  mongo:
    image: mongo
    container_name: developerstore_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16
    container_name: developerstore_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: developerstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d  # Executa os scripts SQL

volumes:
  mongo_data:
  postgres_data:
