version: "3.8"

services:
  api:
    build:
      context: ./src
      dockerfile: DeveloperStore.API/Dockerfile
    ports:
      - "5000:8080"  
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__MongoDb: mongodb://mongo:27017
      # Connection string CORRETA para Npgsql (sem "tcp://")
      ConnectionStrings__DefaultConnection: >
        Host=postgres;Port=5432;Database=developerstore;
        Username=postgres;Password=postgres;Pooling=true

  mongo:
    image: mongo
    container_name: developerstore_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16
    container_name: developerstore_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: developerstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d developerstore"]
      interval: 5s
      timeout: 3s
      retries: 30

  website:
    build:
      context: ./src/DeveloperStore.Website
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
    depends_on:
      - api

volumes:
  mongo_data:
  postgres_data:
